blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/LStuyck/ha-chargepoint-peblar/discussions
    about: For usage questions, ideas, or anything that isn't a bug or feature request.
